delete from SDMNG017 where DNO = 40;
INSERT INTO SDMNG017 (DNO,RECIPT,PRIO,TELOPFLG,TELOPMSG,POPUPFLG,POPUPMSG,SSCMSGFLG,SSCMSG) VALUES (40,81,0,1,'下限検知',0,'下限検知',1,'下限検知');
INSERT INTO SDMNG017 (DNO,RECIPT,PRIO,TELOPFLG,TELOPMSG,POPUPFLG,POPUPMSG,SSCMSGFLG,SSCMSG) VALUES (40,82,0,1,'水検知',0,'水検知',1,'水検知');
